[package]
name = "salsa-macro-rules"
version = "0.24.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Declarative macros for the salsa crate"

[dependencies]

[features]
accumulator = []
