language: rust
sudo: false

rust:
  - nightly
  - beta
  - stable
cache:
  - cargo
matrix:
  allow_failures:
      - rust: nightly
before_install:
  - cargo install mdbook --vers '0.3.1' --debug --force
  - cargo install mdbook-linkcheck --vers '0.4.0' --debug --force
script:
  - RUST_BACKTRACE=1 CARGO_INCREMENTAL=0 cargo test --all
  - RUST_BACKTRACE=1 CARGO_INCREMENTAL=0 cargo test --tests --all
  - RUST_BACKTRACE=1 CARGO_INCREMENTAL=0 cargo test --examples --all
  - cd book && mdbook build && mdbook test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book/book
  keep-history: false
  on:
    branch: master