[book]
authors = ["Salsa Contributors"]
multilingual = false
src = "src"
title = "Salsa"

[build]
create-missing = false

[preprocess.links]

[output.html]
additional-css =["mermaid.css"]
additional-js =["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
# follow-web-links = true --- this is commented out b/c of false errors
traverse-parent-directories = false
exclude = ['bilibili\.com']
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
